#!/usr/bin/env python
# coding: utf-8

import sys
import yaml
import re
import argparse
import subprocess

dns_file = "/var/lib/libvirt/dnsmasq/virbr0.status"

parser = argparse.ArgumentParser(description="Login VM listed in %s" % dns_file)
parser.add_argument(
        "hostname",
        nargs="?",
        type=str,
        help="Login host")
parser.add_argument(
        "-l", "--list", 
        action="store_true",
        help="Show entries")
parser.add_argument(
        "-u", "--update", 
        type=str,
        help="Update hostname by id or ipaddr")
args = parser.parse_args()

print args

def main():
    f = open(dns_file, "r")
    y = yaml.load(f)
    f.close()

    hn = args.hostname
    if args.list == True: # show entries
        i = 0
        for ent in y:
            print("id:%s, host:%s, ipaddr:%s" % (i, ent["hostname"], ent["ip-address"]))
            i += 1
        exit()
    elif args.update != None:
        if re.match(r'^\d+\.\d+\.\d+\.\d+$', args.update):
            h = args.update
        elif re.match(r'^\d+$', args.update):
            idx = int(args.update)
            if idx < len(y):
                h = y[idx]["ip-address"]
        else:
            print("Invalid ipaddr or id!")
            raise

        # Update host name
        subprocess.call([
            "ssh",
            "-t",
            str(h),
            "sudo",
            "hostnamectl",
            "set-hostname",
            str(hn)])
        subprocess.call([
            "ssh",
            "-t",
            str(h),
            "sudo",
            "reboot"])

    
    for ent in y:
        if (ent["hostname"] == hn):
            subprocess.call(["ssh", ent["ip-address"]])


if __name__ == '__main__':
    main()
