#!/usr/bin/env python
# coding: utf-8

import sys
import yaml
import subprocess

dns_file = "/var/lib/libvirt/dnsmasq/virbr0.status"

def show_help():
    print("Login VM listed in %s" % dns_file)
    print("usage: sppsh HOST")

def main():
    f = open(dns_file, "r")
    y = yaml.load(f)
    f.close()

    args = sys.argv
    if len(args) == 1: # show help
        show_help()
        exit()
    elif len(args) > 1:
        if args[1] == "-l": # show entries
            for ent in y:
                print("host: %s, ipaddr: %s" % (ent["hostname"], ent["ip-address"]))
            exit()
        else:  # assign hostname
            hn = args[1]
    else:
        print("Please add option")
        exit()
    
    
    for ent in y:
        if (ent["hostname"] == hn):
            subprocess.call(["ssh", ent["ip-address"]])

main()
